# This disp contains aeverything you can display.

1 = "Live Temperature in F: {temp_f}째"
2 = "Live Temperature in C: {temp_c}째"
3 = "Feels like in F: {feels_temp_f}째"
4 = "Feels like in C: {feels_temp_c}째"
5 = "Wind MPH: {wind_mph} MPH"
6 = "Wind KPH: {wind_kph} KPH"
7 = "Humidity: {humidity}%"
8 = "Pressure: {pressure}"
9 = "Description: {bold}{orange}{description}{orange_OFF}{reset}"